version: "3.8"

# 暫時不做 Blue-Green Deployment
# 開發檢視環境以 failed-fast 取代 rollback
services:

  # port on 8080
  web-backend:
    image: zxc25077667/simple-web-backend:latest
    container_name: web-backend
    networks:
      - swag_web-instance
    restart: unless-stopped

  # port on 8081
  web-frontend:
    image: zxc25077667/simple-web-frontend:latest
    container_name: web-frontend
    networks:
      - swag_web-instance
    restart: unless-stopped

networks:
  swag_web-instance:
    - external: true
